name: validate get and update chg actions
on:
  workflow_dispatch:

jobs:
  test:
    name: test-echo
    runs-on: ubuntu-latest
    steps:
      - name: test1
        uses: ServiceNow/servicenow-devops-change@v2.0.0
        with:
          node-version: '16'
      - name: Output of post_implementation_uat_get
        run: echo "change-request-number = "

  deployment_uat:
    name: Prepare-UAT-Deployment
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow Change Approval
        uses: ServiceNow/servicenow-devops-change@v2.0.0
        id: create
        with:
          node-version: '16'
          devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL_ADEVOPS2 }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID_ADEVOPS2 }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Prepare-UAT-Deployment'
          change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","assignment_group":"b85d44954a3623120004689b2d5dd60a","description":"Automated Software Deployment.","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
          interval: '10'
          timeout: '300'
          
  post_implementation_uat:
       name: Post Implementation UAT GET
       runs-on: ubuntu-latest
       needs: deployment_uat
       outputs:
           changeRequestNumber: ${{ steps.get.outputs.change-request-number }}
       steps:
         - name: ServiceNow Get Change
           uses: ServiceNow/servicenow-devops-get-change@v2.0.0
           id: get
           with:
             node-version: '16'
             devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
             instance-url: ${{ secrets.SN_INSTANCE_URL_ADEVOPS2 }}
             tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID_ADEVOPS2 }}
             context-github: ${{ toJSON(github) }}
             change-details: '{"build_number":"","pipeline_name":"","stage_name":"Prepare-UAT-Deployment"}'

         - name: Output of post_implementation_uat_get
           run: echo "change-request-number = ${{ steps.get.outputs.change-request-number }}" >> $GITHUB_OUTPUT

         - name: Servicenow Update Change Details
           uses: ServiceNow/servicenow-devops-update-change@v2.0.0
           id: update
           with:
             node-version: '16'
             change-request-number: ${{ steps.get.outputs.change-request-number }}
             devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
             tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID_ADEVOPS2 }}
             instance-url: ${{ secrets.SN_INSTANCE_URL_ADEVOPS2 }}
             context-github: ${{ toJSON(github) }}
             change-request-details: '{"close_code":"successful", "close_notes":"Deployment to PROD was successful"}'
